### ISSUE TITLE
Modify Canvas qubit vals if I change qubit values in dialog window

### ISSUE THREAD

**Issue by kburova** [kburova/Quantum-Computer-Simulation#15]
So if if have:

|0> ----------
|0> ----------
|0> ----------

And then I open my dialog and do:

                          0    1    2
            Register X:   1    0    1

canvas should turn into:

|1> ----------
|0> ----------
|1> ----------

If operators were added, they should not change! Only bring circuit vertical bar to the beginning of circuit.
Let me know if you have more questions.

**Comment by RobertFr0st** [comment]
kk, this is really simple, just update the qbits and call show, that functionality is already implimented for reflecting a 1 or 0.

**Comment by kburova** [comment]
Ok, all add that. But If there is going to be time when operators are added, will it redraw those too?

**Comment by RobertFr0st** [comment]
yes, the way show works is it shows the entirety of the canvas.  I trust java to optimize redraw, which according to bvz in 365 is the case.
When we add functions we just need to add that additional draw step of enumerating the function list drawing them in their appropriate places (after erasing the line behind them of course)

**Comment by RobertFr0st** [comment]
just the section of line that would fall behind the function
