### ISSUE TITLE
Come up with logo images for all gates, add diff colors to each type type of gate in drop down Tree

### ISSUE THREAD

**Issue by kburova** [kburova/Quantum-Computer-Simulation#9]
We have Tree View that has verbal explanation of all gates. We Should have logos. 
Or we can get read of tree structure and just have square buttons along vertical pane on a left.
Buttons would match the ones at the top. But we ned to have diff colors for diff types, like let's say
blue for Unary,
green for Binary, and etc.

**Comment by schrismartin** [comment]
### Unary Operators (Due 11:59PM – March 29)
- [x] H (Hadamard)
- [x] I (identity)						
- [x] S (phase gate)
- [x] S† (inverse S) 
- [x] T (𝜋/8)
- [x] X (NOT)						
- [x] √X (Squareroot of NOT)					
- [x] Y (real or/and imaginary)
- [x] Z
### Binary Operators (Due 11:59PM – April 11)
- [x]  CCNOT
- [x]  Swap
- [x] Rotate
### Ternary Operators (Due 11:59PM – April 11)
- [x] Toffoli
### Var-qbit Operators (Due 11:59PM – April 11)
- [x] Grover
- [x] Walsh-Hadamard
- [x] QFT
- [x] Inverse QFT
- [x] General Control
- [x] Function Evaluation
### Error Operators (Due 11:59PM – April 11)
- [x] Error
### Measurements Operators (Due 11:59PM – April 11)
- [x] Computational Basis
- [x] Sign Basis
- [x] Trash
